version: '3.1'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/code/app
    environment:
      - PORT=80
    entrypoint: /start-reload.sh
    depends_on: 
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scraper
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./migrations/v1.sql:/docker-entrypoint-initdb.d/create_database.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_volume:
