CREATE TABLE IF NOT EXISTS cars (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	mileage NUMERIC(10, 2) NOT NULL,
	dealer VARCHAR(100) NOT NULL,
	rating NUMERIC(10, 2) NOT NULL,
	reviews INTEGER NOT NULL,
	price INTEGER NOT NULL
);
