CREATE TABLE IF NOT EXISTS cars (
	id SERIAL PRIMARY KEY,
	brand VARCHAR(100) NOT NULL,
	typeName VARCHAR(100) NOT NULL,
	year INTEGER NOT NULL,
	mileage NUMERIC(10, 2) NOT NULL,
	dealer VARCHAR(100) NOT NULL,
	rating NUMERIC(10, 2) NOT NULL,
	reviews INTEGER NOT NULL,
	price INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS car_import_jobs (
	id SERIAL PRIMARY KEY,
	started_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
	finished_at TIMESTAMP DEFAULT NULL
)
